stages:
  - build

image: node:latest

before_script:
  - npm install

cache:
  paths:
    - node_modules/

build:
  stage: build
  script:
    - npm run build
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
    - npm publish
  only:
    - tags

