stages:
  - build

image: node:latest

before_script:
  - yarn

cache:
  paths:
    - node_modules/

build:
  stage: build
  script:
    - yarn build
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
    - yarn publish --new-version $(git describe --abbrev=0 --tags | awk -F 'v' '{print $2}')
  only:
    - tags

